#!/usr/bin/env sh

# settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   6

# window rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Spotify$" grid=1:1:0:0:1:1 manage=off
